spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fetch_plan?useSSL=false
    username: root
    password: 1991Zxcv
mybatis:
  config-location: classpath:mybatis.xml
server:
  port: 8888
